id: anet_clip_esc



visual_feature_type: ['clip']
visual_feature_folder: ['data/anet/features/clipvitl14.pth']
gt_file_for_eval: ['data/anet/captiondata/val_1.json', 'ata/anet/captiondata/val_2.json']
gt_file_for_para_eval: ['data/anet/captiondata/para/anet_entities_val_1_para.json', 'data/anet/captiondata/para/anet_entities_val_2_para.json']
train_caption_file: data/anet/captiondata/train_modified.json

train_proposal_file: data/generated_proposals/dbg_trainval_top100.json
eval_proposal_file: data/generated_proposals/dbg_trainval_top100.json
dict_file: data/anet/vocabulary_activitynet_thres2.json

train_proposal_type: gt
gt_proposal_sample_num: 30
sample_method: nearest
vocab_size: 8517
invalid_video_json: []
feature_dim: 768
lr: 0.00005
learning_rate_decay_start: 8
learning_rate_decay_every: 3
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
epoch: 30
eval_batch_size: 1
# eval_batch_size: 16
min_epoch_when_save: 2
train_use_amp: False
eval_use_amp: False
# model configs
num_queries: 30
ec_alpha: 1.0
save_dir: save


# grounding settings
# eval_enable_grounding: False
enable_contrastive: False
eval_gt_file_for_grounding: data/anet/captiondata/grounding/val1_for_grounding.json

train_proposal_type: gt
train_proposal_sample_num: 30
sample_method: nearest

batch_size: 1
lr: 0.00005
learning_rate_decay_start: 8
learning_rate_decay_every: 3
learning_rate_decay_rate: 0.5
weight_decay: 0.0001
save_all_checkpoint: 0


epoch: 30

num_queries: 10
dec_layers: 2
enc_layers: 2
transformer_ff_dim: 512
transformer_dropout_prob: 0.1
frame_embedding_num: 200
caption_decoder_type: standard
cap_nheads: 1
cap_dec_n_points: 4
cap_num_feature_levels: 4
soft_attention: 1
att_hid_size: 512

ec_alpha: 1.0

#cost_alpha: 0.5
#cost_gamma: 1
#focal_alpha: 0.5
#focal_gamma: 1
caption_loss_coef: 2
giou_loss_coef: 4
bbox_loss_coef: 0
cls_loss_coef: 2
count_loss_coef: 0.5
max_eseq_length: 20
lloss_cross_entropy: 0
lloss_focal_loss: 0
lloss_gau_mask: 1




with_box_refine: 1
fix_xcw: 1
set_cost_caption: 0
set_cost_giou: 4
set_cost_bbox: 0
set_cost_class: 2
set_cost_cl: 2.0
